CREATE TABLE bronze_air_quality (
    id              SERIAL PRIMARY KEY,
    station_name    VARCHAR(100),
    sido_name       VARCHAR(50),
    data_time       VARCHAR(50),
    pm10_value      VARCHAR(20),
    pm25_value      VARCHAR(20),
    o3_value        VARCHAR(20),
    no2_value       VARCHAR(20),
    co_value        VARCHAR(20),
    so2_value       VARCHAR(20),
    khai_value      VARCHAR(20),
    khai_grade      VARCHAR(10),
    pm10_grade      VARCHAR(10),
    pm25_grade      VARCHAR(10),
    o3_grade        VARCHAR(10),
    no2_grade       VARCHAR(10),
    co_grade        VARCHAR(10),
    so2_grade       VARCHAR(10),
    co_flag         VARCHAR(20),
    pm10_flag       VARCHAR(20),
    pm25_flag       VARCHAR(20),
    no2_flag        VARCHAR(20),
    o3_flag         VARCHAR(20),
    so2_flag        VARCHAR(20),
    loaded_at       TIMESTAMP DEFAULT NOW()
);
